<!DOCTYPE html>
<html lang="en">

<head>
    <!-- Adicione os estilos CSS abaixo -->
    <style>
        body {
            font-family: Arial, sans-serif;
            background-color: #f4f4f4;
            margin: 0;
        }

        .container {
            max-width: 600px;
            margin: 20px auto;
            background-color: #fff;
            padding: 20px;
            border-radius: 5px;
            box-shadow: 0 0 10px rgba(0, 0, 0, 0.1);
        }

        .form-group {
            margin-bottom: 20px;
        }

        label {
            display: block;
            font-weight: bold;
            margin-bottom: 5px;
        }

        input[type="text"],
        input[type="date"],
        input[type="checkbox"],
        select {
            width: 100%;
            padding: 8px;
            box-sizing: border-box;
            margin-bottom: 10px;
        }

        .btn-primary {
            background-color: #013755;
            color: #fff;
            padding: 10px 20px;
            text-decoration: none;
            border-radius: 5px;
            display: inline-block;
        }

        .btn-primary:hover {
            background-color: #012345;
        }

        .btn-back {
            background-color: #ccc;
            color: #000;
            padding: 10px 20px;
            text-decoration: none;
            border-radius: 5px;
            display: inline-block;
            margin-right: 10px;
        }

        .btn-back:hover {
            background-color: #bbb;
        }
    </style>
</head>

<body>
    <div class="container">
        <h2>Buscar Contas</h2>

        <?php
        $form = $this->form;
        $form->setAttribute('action', $this->url('gerenciador-financeiro', ['action' => 'listadoContas']));
        $form->prepare();

        echo $this->form()->openTag($form);
        echo '<div class="form-group">';
        echo '<label for="' . $form->get('dataDesde')->getAttribute('id') . '">Data Desde</label>';
        echo $this->formInput($form->get('dataDesde'));
        echo '</div>';

        echo '<div class="form-group">';
        echo '<label for="' . $form->get('dataFim')->getAttribute('id') . '">Data Fim</label>';
        echo $this->formInput($form->get('dataFim'));
        echo '</div>';

        echo '<div class="form-group">';
        echo $this->formSubmit($form->get('submit'), ['class' => 'btn-primary']);
        echo '</div>';

        // echo '<div class="form-group">';
        // echo '<button type="submit" class="btn-primary" name="' . $form->get('verMesAtual')->getName() . '" id="' . $form->get('verMesAtual')->getAttribute('id') . '" value="' . $form->get('verMesAtual')->getAttribute('value') . '">' . $form->get('verMesAtual')->getLabel() . '</button>';
        // echo '</div>';
        echo $this->form()->closeTag();
        ?>

        <a class="btn btn-back" href="<?= $this->url('menu') ?>">Voltar</a>
    </div>
</body>

</html>
