<?php
/**
 * @var Laminas\View\Renderer\PhpRenderer $this
 */
?>
<!-- <?= $this->doctype() ?> -->
<html lang="pt-BR">
    <head>
        <meta charset="utf-8">
        <?= $this->headTitle('Gerenciador Financeiro')->setSeparator(' - ')->setAutoEscape(false) ?>

        <!-- <link rel="icon" href="public/img/download.png" type="image/png"> -->

        <?= $this->headMeta()
            ->appendName('viewport', 'width=device-width, initial-scale=1.0')
            ->appendHttpEquiv('X-UA-Compatible', 'IE=edge')
        ?>

        <!-- Le styles -->
        <?= $this->headLink([
                                'rel'  => 'shortcut icon',
                                'type' => 'image/vnd.microsoft.icon',
                                'href' => $this->basePath('/img/iconTab.ico')
                            ])
            ->prependStylesheet($this->basePath() . '/css/style.css')
            ->prependStylesheet($this->basePath() . '/css/index.css')
            ->prependStylesheet($this->basePath() . '/css/bootstrap.min.css')
            ->prependStylesheet("https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.1/css/all.min.css")

        ?>

        <!-- Scripts -->
        <?= $this->headScript()
            // ->prependFile($this->basePath() . '/js/gerenciadorFinanceiro.js')
            // ->prependFile('./index.js', 'text/javascript')
            ->prependFile($this->basePath() . '/js/index.js')
            ->prependFile($this->basePath() . '/js/bootstrap.min.js')
            ->prependFile($this->basePath() . '/js/jquery.min.js')
        ?>
    </head>
    <body>
        <div class="">
            <?= $this->content ?>
            <hr>
        </div>
    </body>
</html>
